feat: add observability stack installation option
crusoecloud/slurm pull request #5
Opened 2024-12-13 09:20 UTC by piotrrojek

This is a draft for terraform/ansible changes allowing for observability stack to be installed in the cluster on provisioning.

2025-01-11 22:01 UTC, ApekshaKhilari commented on examples/observability.tfvars
> +enable_observability = true
These vars are not a part of terraform code today. Do we want to add that first?

2025-01-13 20:57 UTC, ApekshaKhilari requested changes

2025-01-13 20:57 UTC, ApekshaKhilari commented on ansible/roles/observability/tasks/setup_nvidia.yml
> +- name: Install NVIDIA Container Toolkit
Need to unhold `nvidia-container-runtime` package first. Otherwise this task fails with 

```
TASK [observability : Install NVIDIA Container Toolkit] ********************************************************************************************************************************************
fatal: [slurm-compute-node-0]: FAILED! => {"cache_update_time": 1736801591, "cache_updated": true, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"       install 'nvidia-container-runtime=3.13.0-1'' failed: E: Held packages were changed and -y was used without --allow-change-held-packages.\n", "rc": 100, "stderr": "E: Held packages were changed and -y was used without --allow-change-held-packages.\n", "stderr_lines": ["E: Held packages were changed and -y was used without --allow-change-held-packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following NEW packages will be installed:\n  nvidia-container-runtime\nThe following held packages will be changed:\n  nvidia-container-runtime\n0 upgraded, 1 newly installed, 0 to remove and 124 not upgraded.\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following NEW packages will be installed:", "  nvidia-container-runtime", "The following held packages will be changed:", "  nvidia-container-runtime", "0 upgraded, 1 newly installed, 0 to remove and 124 not upgraded."]}
```

I tested by unholding the package in my VM directly and then rerunning the play explicitly for only compute nodes and it worked fine.

2025-01-13 21:08 UTC, ApekshaKhilari commented on ansible/roles/observability/tasks/main.yml
> +- name: Setup NVIDIA monitoring on compute nodes
This block runs for ansible inventory group `slurm_compute_nodes`. I checked the inventory and looks like login node is also part of that group. 

```
"slurm_compute_nodes": {
        "hosts": [
            "slurm-compute-node-0",
            "slurm-login-node-0"
        ]
    },
```

so in the case **login node is a c1a instance** (as mentioned in example observability.tfvars), the play fails as c1a instances do not have nvidia driver installed. We should exclude the task from running on non-GPU nodes

```
TASK [observability : Load NVIDIA driver module] ***************************************************************************************************************************************************
fatal: [slurm-login-node-0]: FAILED! => {"changed": false, "msg": "modprobe: ERROR: could not insert 'nvidia': No such device\n", "name": "nvidia", "params": "", "rc": 1, "state": "present", "stderr": "modprobe: ERROR: could not insert 'nvidia': No such device\n", "stderr_lines": ["modprobe: ERROR: could not insert 'nvidia': No such device"], "stdout": "", "stdout_lines": []}
```

2025-01-16 20:23 UTC, piotrrojek commented on ansible/roles/observability/tasks/setup_nvidia.yml
> +- name: Install NVIDIA Container Toolkit
Thanks, good catch!

2025-04-17 18:51 UTC, martin-cala1 approved these changes

2025-04-17 18:52 UTC, martin-cala1 approved these changes

2025-04-18 19:21 UTC, ApekshaKhilari approved these changes

2025-04-22 23:22 UTC, merged